name: CI for Collaboration Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-path=gitleaks.json --report-format=json

  semgrep-scan:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

  zap-scan:
    name: OWASP ZAP Scan via ngrok
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start backend in background
        run: |
          chmod +x ./gradlew
          ./gradlew bootRun &

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget tar

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Expose service via ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          ngrok config add-authtoken "$NGROK_TOKEN"
          ngrok http 8083 > ngrok.log &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels \
            | jq -r .tunnels[0].public_url \
            | sed 's/http:/https:/' \
            > ngrok_url.txt

      - name: Download ZAP v2.16.1
        run: |
          ZAP_VER=2.16.1
          wget https://github.com/zaproxy/zaproxy/releases/download/v${ZAP_VER}/ZAP_${ZAP_VER}_Linux.tar.gz
          tar xzf ZAP_${ZAP_VER}_Linux.tar.gz -C ~
          chmod +x ~/ZAP_${ZAP_VER}/zap.sh

      - name: Run ZAP baseline scan
        run: |
          NGROK_URL="$(cat ngrok_url.txt)"
          ~/ZAP_2.16.1/zap.sh -daemon -host 127.0.0.1 -port 8090 -config api.disablekey=true
          sleep 10
          ~/ZAP_2.16.1/zap-baseline.py \
            -t "$NGROK_URL" \
            -r zap_report.html || true

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
